# Generated by Django 4.0.4 on 2022-10-20 12:04

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('AdFile', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('word', models.FileField(blank=True, null=True, upload_to='word/')),
                ('pptx', models.FileField(blank=True, null=True, upload_to='pptx/')),
                ('zip', models.FileField(blank=True, null=True, upload_to='zip/')),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5000), default=list, size=None)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('VIDEO', 'Video'), ('ARTS', 'Arts & Entertainment'), ('AUTO', 'Auto'), ('BEAUTY', 'Beauty & Fitness'), ('BOOKS', 'Books & Literature'), ('BUSSINESS', 'Business & Industry'), ('FINANCE', 'Finance'), ('FOOD', 'Food & Drink'), ('GAMING', 'Gaming'), ('HEALTH', 'Health'), ('HOBBY', 'Hobbys & Interests'), ('HOME', 'Home & Garden'), ('INERNET', 'Internet & Telcom'), ('JOBS', 'Jobs & Education'), ('LAW', 'Law & Government'), ('NEWS', 'News'), ('COMMUNITIES', 'Online Communities'), ('PEOPLE', 'People & Society'), ('PERFORMANCE', 'Performance'), ('PETS', 'Pets & Animals'), ('REALESTATE', 'Realestate'), ('REFERENCE', 'Reference'), ('SCIENCE', 'Science'), ('SHOPPING', 'Shopping'), ('SPORTS', 'Sports'), ('TRAVEL', 'Travel'), ('WORLD', 'World Localities')], max_length=50)),
                ('Url', models.URLField()),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=10)),
                ('lookup_key', models.CharField(max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Duration in months')),
                ('stripe_product_id', models.CharField(max_length=255)),
                ('stripe_price_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('session_id', models.CharField(max_length=250)),
                ('customer', models.CharField(max_length=255)),
                ('amount_total', models.CharField(max_length=10)),
                ('subscription', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subscription_plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UrlImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('URL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clienturl')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('urlimage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.urlimage')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='results/')),
                ('URL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.urlimage')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='CampaignImages/')),
                ('device', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='CampaignUrl',
            field=models.ManyToManyField(to='app.clienturl'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
