# Generated by Django 4.0.4 on 2022-10-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaignUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaignuploads/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='AdFile',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='CampaignUrl',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='pptx',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='word',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='zip',
        ),
        migrations.CreateModel(
            name='CompainUploadSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('campaignupload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compaignupload')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.size')),
            ],
        ),
        migrations.AddField(
            model_name='compaignupload',
            name='Campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.campaign'),
        ),
    ]
