from django.urls import path
from app import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('register',  views.register_request, name="register"),
    path('login', views.login_request, name="login"),
    path('logout', views.logout_request, name="logout"),
    path('',views.home.as_view(),name='index'),
    path('index',views.home.as_view(),name='index'),
    path('ad-qa',views.adqa.as_view(),name="ad-qa"),
    path('ad-txt-pro',views.adtxtpro.as_view(),name="ad-txt-pro"),
    path('blogs',views.blogs.as_view(),name="blogs"),
    path('about-us',views.aboutus.as_view(),name="about-us"),
    path('pricing',views.pricing.as_view(),name="pricing"),
    path('contactus',views.contactus.as_view(),name="contactus"),
    path('reviews',views.reviews.as_view(),name="reviews"),
    path('screenshot',views.screenshot.as_view(),name="screenshot"),
    path('create-checkout-session',login_required(views.create_checkout_session.as_view(),login_url='login?next=/create-checkout-session'),name="create-checkout-session"),
    path('create-portal-session',login_required(views.customer_portal.as_view(),login_url='login'),name="create-portal-session"),
    path('webhook',views.webhook_received.as_view(),name="webhook"),
    path('success',login_required(views.success.as_view(),login_url='login'),name="success"),
    path('cancel',login_required(views.cancel.as_view(),login_url='login'),name="cancel"),
    path('home/', login_required(views.index.as_view(),login_url='/'), name="home"),
    path('home/<str:page>/', login_required(views.index.as_view(),login_url='/'), name="home"),
    path('create_campaign', login_required(views.create_campaign.as_view(),login_url='/'), name="create_campaign"),
    path('upload_ad', login_required(views.upload_ad.as_view(),login_url='/'), name="upload_ad"),
    path('select_url/<str:Name>/', login_required(views.select_url.as_view(),login_url='/'), name="select_url"),
    path('select_sizes/<str:Name>/', login_required(views.select_sizes.as_view(),login_url='/'), name="select_sizes"),
    path('verify_sizes', login_required(views.verify_sizes.as_view(),login_url='/'), name="verify_sizes"),
    path('view_screenshots/<int:id>/', login_required(views.view_screenshots.as_view(),login_url='/'), name="view_screenshots"),
    path('delete_screenshots/<int:id>/', login_required(views.delete_screenshots.as_view(),login_url='/'), name="delete_screenshots"),
    path("password_reset", views.password_reset_request, name="password_reset"),
    # path('activate/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',views.activate, name='activate'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),
    path("ServerError", views.ServerError.as_view(), name="ServerError"),
    path('selenium/', views.selenium_view, name="selenium"),
    path('ImagePlace/', views.ImagePlace, name="ImagePlace"),
    path('select_url/', views.select_url.as_view(), name="select_url"),
]